Repository googleapis/nodejs-irm, pull requests merged in 2020-05, with the labels that each got.

#188 fix: regenerate unit tests
  synth.metadata
  test/gapic_incident_service_v1alpha2.ts
Labels: automerge, cla: yes

#189 fix: synth.py clean up for multiple version
  src/index.ts
  synth.metadata
  synth.py
Labels: cla: yes

#190 build: do not fail builds on codecov errors (#528)
  .github/workflows/ci.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full
