Repository googleapis/nodejs-irm, pull requests merged in 2020-08, with the labels that each got.

#218 docs: add links to the CHANGELOG from the README.md for Java and Node
  README.md
  synth.metadata
Labels: cla: yes, context: full

#221 build: use gapic-generator-typescript v1.0.7.
  src/v1alpha2/incident_service_client.ts
  synth.metadata
Labels: automerge, cla: yes, context: full

#222 chore: update cloud rad kokoro build job
  .kokoro/release/docs-devsite.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#223 build: perform publish using Node 12
  .kokoro/release/publish.cfg
  synth.metadata
Labels: automerge, cla: yes, context: full

#224 feat(process): add deprecation notice to README and warning
  README.md
  src/index.ts
Labels: cla: yes

#227 build: stop running library generation
  synth.py
Labels: cla: yes
